[package]
name = "tiralab-calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.64"
bevy_utils = "0.8.1"
bstr = "1.0.0"
thiserror = "1.0.34"
flexstr = "0.9.2"